name: Check Version Increase

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - "src/**"

jobs:
  get-main-version:
    uses: ./.github/workflows/manifest-version.yml
    with:
      ref: main

  get-current-version:
    uses: ./.github/workflows/manifest-version.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  check-version:
    runs-on: ubuntu-latest
    needs: [get-main-version, get-current-version]

    steps:
      - run: |
          echo "current: ${{ needs.get-current-version.outputs.version }}"

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: compare versions
        env:
          MAIN_VERSION: ${{ needs.get-main-version.outputs.version }}
          CURRENT_VERSION: ${{ needs.get-current-version.outputs.version }}
        run: test "$MAIN_VERSION" != "$CURRENT_VERSION"
