name: create tag when PR is merged

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "src/**"

jobs:
  get-version:
    uses: ./.github/workflows/manifest-version.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  create-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: get-version
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4

      - name: create tag
        run: git tag ${{ needs.get-version.outputs.version }}

      - name: push tag
        run: git push origin ${{ needs.get-version.outputs.version }}
