name: "Release: Attach Artifact"

on:
  release:
    types:
      - released
      - prereleased

permissions: write-all

env:
  FILE_NAME: nitech-moodle-extension-40a-${{ github.event.release.tag_name }}.zip

jobs:
  attach-build-artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: build
        run: deno task build

      - name: zip artifacts
        run: cd ./dist; zip $FILE_NAME -r .

      - name: upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} $FILE_NAME
